name: nidus

on:
  schedule:
    - cron: "5 9 * * *"
  
  # For manual　execution
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    env:
      SLACK_BOT_USER_OAUHT_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUHT_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Execute nidus
        run: python notify.py ${SLACK_BOT_USER_OAUHT_TOKEN}
